const CHROME_SQUARE_BUTTON_REM = 1.9;
const CHROME_ACTION_BUTTON_MIN_WIDTH = '6.25rem';
const CHROME_CONTROL_BUTTON_WIDTH_REM = 6.6;
const CHROME_CONTROL_BUTTON_HEIGHT_REM = 1.45;
const CHROME_DIRECTION_BUTTON_GAP_REM = 0.25;
const CHROME_CONTROL_COLUMN_PADDING_REM = 0.7;
const CHROME_PLACEMENT_COLUMN_GAP_REM = 0.9;
const CHROME_PLACEMENT_SECTION_GAP_REM = 0.22;
const CHROME_SHAPE_GRID_COLUMNS = 5;
const CHROME_RADIUS_COLUMN_WIDTH_REM = 5.2;

const toRem = (value: number) => `${value}rem`;

const CHROME_SQUARE_BUTTON_SIZE = toRem(CHROME_SQUARE_BUTTON_REM);
const CHROME_CONTROL_BUTTON_WIDTH = toRem(CHROME_CONTROL_BUTTON_WIDTH_REM);
const CHROME_CONTROL_BUTTON_HEIGHT = toRem(CHROME_CONTROL_BUTTON_HEIGHT_REM);
const CHROME_DIRECTION_BUTTON_GAP = toRem(CHROME_DIRECTION_BUTTON_GAP_REM);
const CHROME_DIRECTION_COMPASS_WIDTH = toRem(
  CHROME_SQUARE_BUTTON_REM * 3 + CHROME_DIRECTION_BUTTON_GAP_REM * 2,
);
const CHROME_DIRECTION_COLUMN_WIDTH = toRem(
  Math.max(
    CHROME_CONTROL_BUTTON_WIDTH_REM,
    CHROME_SQUARE_BUTTON_REM * 3 + CHROME_DIRECTION_BUTTON_GAP_REM * 2,
  ),
);
const CHROME_CONTROL_COLUMN_PADDING = toRem(CHROME_CONTROL_COLUMN_PADDING_REM);
const CHROME_PLACEMENT_COLUMN_GAP = toRem(CHROME_PLACEMENT_COLUMN_GAP_REM);
const CHROME_PLACEMENT_SECTION_GAP = toRem(CHROME_PLACEMENT_SECTION_GAP_REM);
const CHROME_SHAPE_COLUMN_WIDTH = toRem(
  CHROME_SQUARE_BUTTON_REM * CHROME_SHAPE_GRID_COLUMNS +
    CHROME_DIRECTION_BUTTON_GAP_REM * (CHROME_SHAPE_GRID_COLUMNS - 1),
);
const CHROME_RADIUS_COLUMN_WIDTH = toRem(CHROME_RADIUS_COLUMN_WIDTH_REM);

const CHROME_SHARED_CENTER_STYLE = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  textAlign: 'center' as const,
  lineHeight: '1',
};

const CHROME_ACTION_BUTTON_STYLE = {
  ...CHROME_SHARED_CENTER_STYLE,
  minWidth: CHROME_ACTION_BUTTON_MIN_WIDTH,
  minHeight: CHROME_SQUARE_BUTTON_SIZE,
  height: CHROME_SQUARE_BUTTON_SIZE,
  padding: '0 0.55rem',
  marginRight: '0',
  marginBottom: '0',
};

const CHROME_ICON_BUTTON_STYLE = {
  ...CHROME_SHARED_CENTER_STYLE,
  width: CHROME_SQUARE_BUTTON_SIZE,
  minWidth: CHROME_SQUARE_BUTTON_SIZE,
  height: CHROME_SQUARE_BUTTON_SIZE,
  minHeight: CHROME_SQUARE_BUTTON_SIZE,
  padding: '0',
  marginRight: '0',
  marginBottom: '0',
};

const CHROME_CONTROL_BUTTON_STYLE = {
  ...CHROME_SHARED_CENTER_STYLE,
  width: CHROME_CONTROL_BUTTON_WIDTH,
  minWidth: CHROME_CONTROL_BUTTON_WIDTH,
  maxWidth: CHROME_CONTROL_BUTTON_WIDTH,
  minHeight: CHROME_CONTROL_BUTTON_HEIGHT,
  height: CHROME_CONTROL_BUTTON_HEIGHT,
  padding: '0 0.4rem',
  fontSize: '0.92rem',
  marginRight: '0',
  marginBottom: '0',
};

const DIRECTION_BUTTON_LABELS: Record<string, string> = {
  north: 'С',
  east: 'В',
  south: 'Ю',
  west: 'З',
};

export {
  CHROME_ACTION_BUTTON_STYLE,
  CHROME_CONTROL_BUTTON_HEIGHT,
  CHROME_CONTROL_BUTTON_STYLE,
  CHROME_CONTROL_BUTTON_WIDTH,
  CHROME_CONTROL_COLUMN_PADDING,
  CHROME_DIRECTION_BUTTON_GAP,
  CHROME_DIRECTION_COLUMN_WIDTH,
  CHROME_DIRECTION_COMPASS_WIDTH,
  CHROME_ICON_BUTTON_STYLE,
  CHROME_PLACEMENT_COLUMN_GAP,
  CHROME_PLACEMENT_SECTION_GAP,
  CHROME_RADIUS_COLUMN_WIDTH,
  CHROME_SHAPE_COLUMN_WIDTH,
  CHROME_SHAPE_GRID_COLUMNS,
  CHROME_SHARED_CENTER_STYLE,
  CHROME_SQUARE_BUTTON_SIZE,
  DIRECTION_BUTTON_LABELS,
};
